/*
install [this](https://httpyac.github.io/guide/) and run test
*/
@host=http://localhost:8080
?? status == 200
?? header content-type exists
###
# test index
GET /
?? header content-type == text/html; charset=UTF-8

?? body == {{< ./index.html}}
# >>! ./index.html

HTTP/1.1 200  - OK
x-frame-options: DENY
content-length: 1475
content-type: text/html; charset=UTF-8
###
# test /dir toc
GET /dir
?? header content-type == text/html; charset=UTF-8

?? body == {{< ./dir.html}}
# >>! ./dir.html

HTTP/1.1 404  - Not Found
content-length: 0
content-type: text/html
###
GET /dir/test.md
?? header content-type == text/html; charset=UTF-8

?? body == {{< ./dir/test.md.html}}
# >>! ./dir/test.md.html

HTTP/1.1 404  - Not Found
content-length: 0
content-type: text/html
###
GET /dir/test.txt
?? header content-type == text/plain; charset=UTF-8

?? body == {{< ./dir/test.txt.html}}
# >>! ./dir/test.txt.html

HTTP/1.1 404  - Not Found
content-length: 0
content-type: text/html