/*
install [this](https://httpyac.github.io/guide/) and run test
*/
@host=http://localhost:8080
?? status == 200
?? header content-type exists
###
# test index
GET /
?? header content-type == text/html; charset=utf-8

?? body == {{< ./index.html}}

HTTP/1.1 200  - OK
transfer-encoding: chunked
connection: close
content-encoding: br
content-type: text/html; charset=utf-8
vary: accept-encoding
date: Mon, 13 Oct 2025 01:51:50 GMT
###
# test /dir toc
GET /dir
?? header content-type == text/html; charset=utf-8

?? body == {{< ./dir.html}}

HTTP/1.1 200  - OK
transfer-encoding: chunked
connection: close
vary: accept-encoding
content-type: text/html; charset=utf-8
content-encoding: br
date: Mon, 13 Oct 2025 01:51:51 GMT
###
GET /dir/test.md
?? header content-type == text/html; charset=utf-8

?? body == {{< ./dir/test.md.html}}

HTTP/1.1 200  - OK
transfer-encoding: chunked
connection: close
content-encoding: br
content-type: text/html; charset=utf-8
vary: accept-encoding
date: Mon, 13 Oct 2025 01:51:51 GMT
###
GET /dir/test.txt
?? header content-type == text/plain; charset=utf-8

?? body == {{< ./dir/test.txt.html}}

HTTP/1.1 200  - OK
transfer-encoding: chunked
connection: close
etag: "0:22:68ea1130:218714c0"
content-disposition: inline; filename="test.txt"
vary: accept-encoding
accept-ranges: bytes
content-type: text/plain; charset=utf-8
content-encoding: br
last-modified: Sat, 11 Oct 2025 08:11:28 GMT
date: Mon, 13 Oct 2025 01:51:52 GMT