name: test
permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  test-with-httpyac:
    if: false
    runs-on: ubuntu-latest
    name: test with httpyac
    env:
      PORT: 1234
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4

      - name: Install netcat
        run: |
          if ! command -v nc &> /dev/null; then
            apt-get update && apt-get install -y netcat-openbsd
          fi

      - run: cargo b
      - run: echo "PORT=${{ env.PORT }}" > .env
      - run: cargo run  -- port ${{ env.PORT }} &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost ${{ env.PORT }}; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 1
            fi
          done

      - name: test
        id: test
        run: npx httpyac send test/test.http -a -e ./.env

      - run: rm ./.env

  cargo-test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
        with:
          cache-all-crates: true

      # actions-rust-lang/setup-rust-toolchain is Caching for Rust tools and build artifacts is enabled.

      - uses: taiki-e/install-action@7bc99eee1f1b8902a125006cf790a1f4c8461e63 # v2.69.8
        with:
          tool: cargo-make

      - run: cargo make cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/nextest/ci/junit.xml
          report_type: test_results
