name: test
permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  test-with-httpyac:
    if: false
    runs-on: ubuntu-latest
    name: test with httpyac
    env:
      PORT: 1234
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0

      - name: Install netcat
        run: |
          if ! command -v nc &> /dev/null; then
            apt-get update && apt-get install -y netcat-openbsd
          fi

      - run: cargo b
      - run: echo "PORT=${{ env.PORT }}" > .env
      - run: cargo run  -- port ${{ env.PORT }} &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost ${{ env.PORT }}; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 1
            fi
          done

      - name: test
        id: test
        run: npx httpyac send test/test.http -a -e ./.env

      - run: rm ./.env

  cargo-test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        with:
          cache-all-crates: true

      # actions-rust-lang/setup-rust-toolchain is Caching for Rust tools and build artifacts is enabled.

      - uses: taiki-e/install-action@5939f3337e40968c39aa70f5ecb1417a92fb25a0 # v2.75.15
        with:
          tool: cargo-binstall just cargo-all-features cargo-nextest cargo-llvm-cov

      - run: just cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/nextest/ci/junit.xml
          report_type: test_results
