name: test
permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  test-with-httpyac:
    if: false
    runs-on: ubuntu-latest
    name: test with httpyac
    env:
      PORT: 1234
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0

      - name: Install netcat
        run: |
          if ! command -v nc &> /dev/null; then
            apt-get update && apt-get install -y netcat-openbsd
          fi

      - run: cargo b
      - run: echo "PORT=${{ env.PORT }}" > .env
      - run: cargo run  -- port ${{ env.PORT }} &

      - name: Wait for server to be ready
        run: |
          for i in {1..10}; do
            if nc -z localhost ${{ env.PORT }}; then
              echo "Server is up!"
              break
            else
              echo "Waiting for server..."
              sleep 1
            fi
          done

      - name: test
        id: test
        run: npx httpyac send test/test.http -a -e ./.env

      - run: rm ./.env

  cargo-test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          cache-all-crates: true

      # actions-rust-lang/setup-rust-toolchain is Caching for Rust tools and build artifacts is enabled.

      - uses: taiki-e/install-action@c93ccc03e00cd0e08e494f5fd058a6c55a6a1907 # v2.82.8
        with:
          tool: cargo-binstall just cargo-hack cargo-nextest cargo-llvm-cov

      - run: just cov

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./lcov.info
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/nextest/ci/junit.xml
          report_type: test_results
